### ISSUE TITLE
sensu-plugins-lvm repository

### ISSUE THREAD

**Issue by insom** [sensu-plugins/community#10]
Hi,

Can a sensu-plugins-lvm repository please be created? I've created a check and a metric to monitor the free and used space in a volume group, modelled after the *-disk-* checks.

https://github.com/insom/sensu-plugins-lvm

I'm not certain on some of the packaging, but as with my Gearman repository have copied as much as possible from the existing sensu-plugins-\* structure.

**Comment by cwjohnston** [comment]
Hi @insom, thanks for getting in touch with this contribution to the Sensu plugins project! I see a release for this project was successfully published to rubygems. I installed the gem successfully, so it seems like the packaging is 👍 .

If you will transfer the repository to me, believe I have sufficient privileges to transfer the repository to the sensu-plugins org.

**Comment by insom** [comment]
@cwjohnston There you go, sorry about the delay, Friday was an ... eventful day here in the UK.
