### ISSUE TITLE
improvement of sensu-salt

### ISSUE THREAD

**Issue by x70b1** [sensu-plugins/community#100]
@majormoses @mbbroberg @perlchild

The SaltStack section needs a bit more love. 

We should think about how we want organize furher development. 
The previous repository must be tested and kept up to date. 
In addition, a development for Sensu 2.0 is useful.

**Comment by majormoses** [comment]
I am :+1: right now for anyone willing to help on the saltstack front as there is definitely need of som love there. Now that we will have 2 maintainers for it we will start becoming more restrictive on who becomes maintainers and will only consider new maintainers after they have contributed consistently good code on multiple occasions.

@mbbroberg as it requires someone with access to the `sensu` org we need you to minimally do that part if you want I can take care of the other stuff. Totally up to you.

**Comment by mbbroberg** [comment]
💯on this thread. I've given you both W on https://github.com/sensu/sensu-salt/ (@x70b1 for maintaining it alongside @perlchild and @majormoses as an OSS mentor to them). I love seeing what you're thinking on https://github.com/sensu/sensu-salt/issues/3 and find this to be the best place that we keep working toward a shared vision. It's exciting 🥇 

@x70b1 is there anything else you want to discuss here before we close it?

**Comment by x70b1** [comment]
@mbbroberg, thanks a lot!
I think it's all said for the moment.
