### ISSUE TITLE
Connect conversations across Slack & IRC

### ISSUE THREAD

**Issue by mbbroberg** [sensu-plugins/community#101]
Here's a short story with an idea. The maintainers of Sensu made the call to focus on Slack as the primary real-time communication platform ([FAQ is here](https://github.com/sensu-plugins/community/blob/master/HOW_WE_SLACK.md#faq)) and it's resulted in a much more organized multichannel flow of conversation. From there, the strategy was to tell IRC users to join Slack and primarily ignore future traffic to IRC. 

It's here that I feel it's worth revisiting. 

There continues to be quick questions dropping in IRC on a regular basis community continues to 
Sameroom has been in place as a bridge, sending a max of a few messages per day. New users are coming by IRC. I think it might be best to get these conversations more eyes.

### Data 

There's been 1-3 messages every 5 days for the last month. Previous to that, one question every day or two. All of these are visible in `#irc-link` in our [Community Slack](http://slack.sensu.io). 

## Proposal 

Use Sameroom to stream all content to a primary channel of Slack. I lean toward `#monitoringlove` as its our primary channel. 

## Benefits

Don't lose contact with new users who are IRC focused. 

## Risk 

Spam content will stream into our Slack team and require more administration. We also have the pain of **people disappearing before they receive answers to their question**, which is my biggest challenge with IRC.

## RFC

What do others feel is the right move?

**Comment by majormoses** [comment]
I am a bit torn personally I see pros and cons of each. Here are some things to consider beyond the ones outlined above.

## Pros:
- users who like IRC are not left behind
- at that low of a volume it is not much extra maintenance/admin/noise

## Cons:
- it discourages people from taking chats to the appropriate channels to avoid clutter
- it sends the message that we will keep policing IRC and reinforcing bad slack habits which reduce the quality of the overall experience

## My $0.02
I am fine with enabling it for now with such low volume but if the volume starts picking up then I think we should revert to keeping it `#irc-link` channel which tbh I was not even aware existed. I probably would have peaked inside every once in a while (I did that in IRC itself for a while after the transition) if I knew it was there, even if just pointing them to slack or docs to help set up irc client with slack. That being said I think we need to have some number of people who very active members in slack as maintainers, contributors, and users agree that the benefit is better the risk. I do not think this decision should be made without all types of users being able to weigh in.

**Comment by portertech** [comment]
I'm all for giving it a whirl 👍 If it proves to be a problem, or Slack users are unable to effectively communicate with and help IRC users, we can always rethink it!

**Comment by mbbroberg** [comment]
The experiment is a go! We're up and running in `#monitoringlove`. Let's see how it goes! 

<img width="774" alt="screen shot 2018-04-03 at 8 58 07 am" src="https://user-images.githubusercontent.com/1744971/38260696-2c03f790-371d-11e8-87f9-04ddd88e4563.png">
