### ISSUE TITLE
Configuration Management + Sensu Core 2.0

### ISSUE THREAD

**Issue by mbbroberg** [sensu-plugins/community#103]
## Update
After thoughtful discussion on the naming convention of repositories and packages, and considering how version numbers is NOT good to instantiate in names, I'm shifting recommendations to be around.

--- 
With the [open sourcing of Sensu Core 2.0](https://github.com/sensu/sensu-go), we have a lot of excitement around deployment options. I'd like to propose we follow some convention across each project to get there. Initial idea: 

- ~Every project starts a `sensu2-compatibility` branch~ 
- ~Each project, if maintainers use milestones, create one called `Sensu Core 2.0 Compatibility`~
- ~Any issues that are specific to the project are created and added to the milestone.~

Wdyt everyone? 

Pulling maintainer info from the README + the TODO of adding our SaltStack maintainer: 

| Area                         | Major Links                                                    | Maintainers                                                                                                                                        | Needs Contributors?                                                                           |
|:-----------------------------|:---------------------------------------------------------------|:---------------------------------------------------------------------------------------------------------------------------------------------------|:----------------------------------------------------------------------------------------------|
| ![Puppet][puppet_pic]        | [Puppet Module][puppet]                                        | **[Garrett (@ghoneycutt) - Lead](https://github.com/ghoneycutt)**                                                                                  | **Yes!** [Help review issues.](https://github.com/sensu/sensu-puppet/issues)                  |
| ![Chef][chef_pic]            | [Chef Cookbook][chef_sensu]</br>[Uchiwa Cookbook][chef_uchiwa] | **[Ben (@majormoses) - Lead][9]**</br>[Tom (@thomasriley)][18]                                                                                     | **Yes!** [Help review issues.](https://github.com/sensu/sensu-chef/issues)                    |
| ![Ansible][ansible_pic]      | [Ansible Role][ansible]</br>[Ansible Module][ans_module]       | **[Jared (@jaredledvina) - Lead][19]**</br>[Chris (@cjchand)][21]</br>[Calum (@cmacrae)][20]                                                       | **Yes!** [Help review issues.](https://github.com/sensu/sensu-ansible/issues)                 |
| ![SaltStack][salt_pic]       | [SaltStack Formula][saltstack]                                 |   **Eric R (@perlchild)**                                                                                                                                                 | **Yes!** [Please volunteer.](https://github.com/sensu-plugins/community/issues/79)            |

[sensu_pic]: https://avatars0.githubusercontent.com/u/10713628?s=50
[ruby_pic]: https://avatars2.githubusercontent.com/u/210414?s=50
[python_pic]: https://avatars0.githubusercontent.com/u/1525981?s=50
[windows_pic]: https://user-images.githubusercontent.com/1744971/32962538-aff30f08-cb81-11e7-86c2-b8aa226d211d.png
[puppet_pic]: https://avatars1.githubusercontent.com/u/9100?s=50
[chef_pic]: https://avatars3.githubusercontent.com/u/29740?s=50
[salt_pic]: https://avatars2.githubusercontent.com/u/1147473?s=50
[ansible_pic]: https://avatars1.githubusercontent.com/u/1507452?s=50
[plug_org]: https://github.com/sensu-plugins
[ext_org]: https://github.com/sensu-extensions
[ruby_lib]: https://github.com/sensu-plugins/sensu-plugin
[py_lib]: https://github.com/sensu-plugins/sensu-plugin-python
[windows]: https://github.com/sensu-plugins/sensu-plugins-windows
[saltstack]: https://github.com/sensu/sensu-salt
[puppet]: https://github.com/sensu/sensu-puppet
[chef_sensu]: https://github.com/sensu/sensu-chef
[chef_uchiwa]: https://github.com/sensu/uchiwa-chef
[ansible]: https://github.com/sensu/sensu-ansible
[ans_module]: https://github.com/ansible/ansible/tree/devel/lib/ansible/modules/monitoring
[volunteer]: https://github.com/sensu-plugins/community/blob/master/CONTRIBUTING.md
[py_helpwanted]: https://github.com/sensu-plugins/sensu-plugin-python/issues?q=is%3Aissue+is%3Aopen+label%3A%22Status%3A+Help+Wanted%22
[11]: https://github.com/sstarcher
[9]: https://github.com/majormoses
[10]: https://github.com/eheydrick
[12]: https://github.com/luisdavim
[13]: https://github.com/sstarcher
[15]: https://github.com/mattyjones
[14]: https://github.com/barryorourke
[16]: https://github.com/calebhailey
[17]: https://github.com/cwjohnston
[18]: https://github.com/thomasriley
[19]: https://github.com/jaredledvina
[20]: https://github.com/cmacrae
[21]: https://github.com/cjchand
[22]: https://github.com/absolutejam

**Comment by majormoses** [comment]
I think this is a good idea and aligns with what I outlined in saltstack when discussing the go forward path with the maintainers. I think we need to call out our support plan. Moving from 1.x -> 2.x will not be a smooth transition for most people and I would expect we will need to continue to support both 1.x and 2.x solutions for a while.

As originally proposed I think that we should create a new branch called `sensu-1.x` from master, and create a `sensu-2.x` branch either from master or blank branch with nothing on it. Additionally I would encourage renaming the cookbooks, playbooks, formulas to `sensu2` so that we can follow semver without having conflicting versions between two different products.  We will want to add messaging around this and do a full major version upgrade so that anyone pulling master but pinning on specific versions will be unaffected. At some point master will be the branch that becomes the equivalent of "development" for `sensu-2.x` branch. Now to the main point I was going to make is that we need to support them both for a while. I think that we should take an approach like this:
- 6 months of feature development of `sensu-1.x` after sensu 2 is GA
- 6 months of additional of bug fixing of `sensu-1.x` which leads to a total of 1 year of support on `sensu-1.x`

After the first 6 months we would make master the pre-release branch for `sensu-2.x` and any `sensu-1.x` work would be made directly to the release branch. At that point we would no take a stance of not putting any more effort into supporting `sensu-1.x` but would allow reviewing of bug and security fixes only from the community, no features allowed period.

An alternate approach would be to create new repos such as `sensu2-chef` and start from scratch this eliminates many of the extra complexity but the same support principles would apply. I think this is probably the better approach IMHO even though I originally proposed the first idea.

**Comment by thomasriley** [comment]
> An alternate approach would be to create new repos such as sensu2-chef and start from scratch this eliminates many of the extra complexity but the same support principles would apply. I think this is probably the better approach IMHO even though I originally proposed the first idea.

I find that it does tend to be easier to develop in a greenfield space, so it is a +1 from me on creating a new repo. Makes it easier to support & release both versions side by side removing any complexity explained above (until the support for sensu 1.x expires as explained above by Ben).

**Comment by mbbroberg** [comment]
@thomasriley @majormoses good points. Let me review what @portertech had planned - he was hacking on Chef work as well - and circle back here today.

**Comment by mbbroberg** [comment]
@majormoses @thomasriley I just created `sensu-go-chef` with a few heads up to keep in mind: 

* We may rename the repo based on packaging naming decisions 
* If at some point in the future we there is sponsored support for the repo, non-maintainers might make more design decisions

With that in mind: https://github.com/sensu/sensu-go-chef

**Comment by mbbroberg** [comment]
Note the update to the description - separate repos that align to the `sensu-go` repo name is a good first step. No one here is required to work on it of course, but let me know if you're interested and I'll link you into plans coming out of Core engineering team.

**Comment by x70b1** [comment]
@mbbroberg this means the new standard is `sensu-go-*`? Did I understand that right?
Another example: `sensu-go-salt`? I'm asking for a friend. :sunglasses:

**Comment by majormoses** [comment]
That is the current go forward naming convention which is currently something that I consider still up for debate and subject to change as we are still in alpha.

**Comment by mbbroberg** [comment]
Hey @x70b1! Yes, that's the plan for now. I'll update this issue as we evolve the plan, but this plan is solid for our Alpha phase right now. Specifically talking about Salt, if you're ready to go and @perlchild doesn't mind, I could setup the new repo for you two as well :slightly_smiling_face:. Wdyt?

**Comment by x70b1** [comment]
It was just so that I could understand. I think if we actually need the repo, we'll let you know.

**Comment by jaredledvina** [comment]
I think we're alright here, looking forward we have the following as of today:
# Ansible
* Sensu Core: https://github.com/sensu/sensu-ansible
* Sensu Go: https://github.com/sensu/sensu-go-ansible

# Chef
* Sensu Core: https://github.com/sensu/sensu-chef
* Sensu Go: https://github.com/sensu/sensu-go-chef

# Puppet
* Sensu Core: https://forge.puppet.com/sensu/sensuclassic
* Sensu Go: https://github.com/sensu/sensu-puppet

# SaltStack
* https://github.com/sensu/sensu-salt - Unsure as to the status here, I've never used SaltStack. 


I'll close this out for now, feel free to reopen if anyone feels that there's still work to do here.
