### ISSUE TITLE
Create a new plugin for salesforce

### ISSUE THREAD

**Issue by mohanrao** [sensu-plugins/community#108]
Let's have a handler to publish a case in the salesforce for the events

**Comment by majormoses** [comment]
I will get the base skel in place and you can work on creating the handler itself, will try to find some time to do it this weekend.

**Comment by majormoses** [comment]
I have done most of the initial work and will complete it either monday or tues: https://github.com/sensu-plugins/sensu-plugins-salesforce

**Comment by majormoses** [comment]
I pushed the basic skel to master, look forward to reviewing your PR to add handler.
