### ISSUE TITLE
Create sensu-plugins-nrpe repo

### ISSUE THREAD

**Issue by scosist** [sensu-plugins/community#11]
Please create a repository for sensu-plugins-nrpe. I created a check and a metric to monitor NRPE check results, modeled after the sensu-plugins-snmp repo.

https://github.com/scosist/sensu-plugins-nrpe

**Comment by majormoses** [comment]
I have created the skel, please make prs against it: https://github.com/sensu-plugins/sensu-plugins-nrpe @mattyjones ping on permissions

**Comment by scosist** [comment]
Thanks, I have a PR ready to push once permission has been granted.

**Comment by majormoses** [comment]
@scosist while that gets sorted I am more than happy to moderate PRs.

**Comment by eheydrick** [comment]
Rubygems deploy bits added and 0.2.1 is [live on Rubygems](https://rubygems.org/gems/sensu-plugins-nrpe/versions/0.2.1)! Is there anything else needed before we close this out?

**Comment by scosist** [comment]
Awesome, looks good to me. Thanks!
