### ISSUE TITLE
Configuration Management: How do we want to handle documentation?

### ISSUE THREAD

**Issue by jaredledvina** [sensu-plugins/community#111]
Related to https://github.com/sensu-plugins/community/issues/103 

While we are working on the Sensu Go/2Alpha/Beta configuration management repos, how would we like to handle documentation about our various cookbooks, roles, modules, etc? 

Currently, for Ansible, I'm planning to start off while most of the docs simply in the README, as that will automatically get pulled into https://galaxy.ansible.com/ when the role is official. 

However, I'm totally game to align work between the CM tools so that the UX is similar. 

Curious to know what everyone prefers!

**Comment by majormoses** [comment]
In the chef world we mostly rely on `README.md` which when is pushed to the `supermarket` this will show up as well.

**Comment by jaredledvina** [comment]
Sounds like everyone's going to do their own thing via the README and their platform specific setup, no further action needed for now.
