### ISSUE TITLE
sensu-plugins-tomcat repository

### ISSUE THREAD

**Issue by smbambling** [sensu-plugins/community#12]
Can you please create a sensu-plugins-tomcat repository, or allow me to transfer the current repo in my personal repo to the sensu plugins ORG https://github.com/smbambling/sensu-plugins-tomcat

I believe in the dev docs it stated I would have read/write access to this new repository as well, is that correct ?

Additionally I have several members of my team that we would want to have access to this repo as well, is that an issue ?

**Comment by smbambling** [comment]
Until this is accepted or not I have moved the repo here https://github.com/arineng/sensu-plugins-tomcat

**Comment by smbambling** [comment]
Any status on this, I have two other plugins that I would like to submit if this one is in the correct format.

https://github.com/arineng/sensu-plugins-switchvox and
https://github.com/arineng/sensu-plugins-jolokia

**Comment by majormoses** [comment]
@smbambling apologies on the delay I will create a skeleton repo that you can open up prs against. I am quite new as a maintainer and would defer to @mattyjones on granting permissions.

**Comment by majormoses** [comment]
@smbambling new repo: https://github.com/sensu-plugins/sensu-plugins-tomcat

**Comment by smbambling** [comment]
This is great thanks so much, any chance you can make me two other repos for the other projects ?

**Comment by majormoses** [comment]
@smbambling sure, just open an issue per repo and I can certainly create repos, again as I am new as a maintainer (been a contributor for several years) I would like to have another member handle the discussion about granting external access. I plan on being responsive, so in the mean time You can always fork and submit PRs.

**Comment by majormoses** [comment]
@smbambling can we close this and open the 2 issues for the 2 new plugins?

**Comment by smbambling** [comment]
Yep, i'll open issues for the other repos once we get all the tomcat stuff ironed out. Thanks for the help with this.
