### ISSUE TITLE
How to handle PRs from Dependabot?

### ISSUE THREAD

**Issue by lagartoflojo** [sensu-plugins/community#123]
The plugin I maintain has many open PRs created by Dependabot (https://github.com/sensu-plugins/sensu-plugins-telegram/pulls).
How should we handle those? Who should merge them? I searched for "dependabot" in this repo, but found no mention of it.

Thanks!

**Comment by majormoses** [comment]
Hey I started setting up dependabot to look for old dependencies and automatically create pull requests. Like any pull request we should be evaluating them for impact. If they do not require a breaking change they can be merged, added to the changelog, and released. If they require breaking changes we have to make a decision on when/how we implement it and message that back to our users.

**Comment by lagartoflojo** [comment]
Makes sense, but you mentioned you were trying to get all plugins on the same version of Rubocop (0.51.0). Do you have any restrictions like that on other gems? Otherwise, I would merge and add to the changelog the PRs that are open.

**Comment by majormoses** [comment]
rubocop is kinda special in that regard, the only other one would be `sensu-plugin` we should always use the `~> MAJOR.MINOR` (optional patch) format as we actually follow semver and spanning multiple versions is not actually doable. I still review each of them to make sure there are not any breaking changes that we need to account for but yes in general merge, updating changelog, version, and release.

**Comment by majormoses** [comment]
Ideally we should be on `~> 3.0` of `sensu-plugin` but if its still locked on `~> 1.2` thats a breaking change which we can do we just need to make sure we communicate and version it properly as otherwise it will break people who have properly pinned their versions using some kind of constraints (at least at the major level)

**Comment by majormoses** [comment]
Let me know if you need any more guidance
