### ISSUE TITLE
Transfer sensu-plugins-rocket-chat

### ISSUE THREAD

**Issue by lagartoflojo** [sensu-plugins/community#124]
## Transfer Ownership

We would like to transfer the ownership of this plugin to the sensu-plugins organization in hopes of better community support and exposure. I have reviewed [the skeleton plugin](https://github.com/sensu-plugins/sensu-plugins-skel) for best practices.

Repo to transfer: https://github.com/lagartoflojo/sensu-plugins-rocket-chat

I am also interested in continuing to help as a maintainer of this plugin 👍

**Comment by lagartoflojo** [comment]
Ping @majormoses :)

**Comment by majormoses** [comment]
Oh shoot I forgot about this through the holidays.

To transfer the repo you can read through how to do it here: https://github.com/sensu-plugins/community/blob/master/TRANSFERRING_REPOS.md you can transfer it to me and I can transfer it to the org.

If you can get it transferred today I will make sure it gets CI + CD and such setup over the weekend.

**Comment by majormoses** [comment]
It has been transferred over: https://github.com/sensu-plugins/sensu-plugins-rocket-chat I will try to get CI setup this weekend (probably this evening).

**Comment by majormoses** [comment]
I have updated the travis config for rubygems deploys. It should auto deploy releases on tags. Let me know if you need any help.

**Comment by lagartoflojo** [comment]
Thanks a lot @majormoses !!
