### ISSUE TITLE
RFE: First class VMware vSphere checks

### ISSUE THREAD

**Issue by portertech** [sensu-plugins/community#13]
FROM @jflemer-ndp - https://github.com/sensu/sensu/issues/1527

*Request For Enhancement*: Provide a (public or enterprise) extension or plugin with first class monitoring of vSphere.

## Expected Behavior
`sudo sensu-install -p vsphere`

## Current Behavior
Maybe use Nagios plugins, pulling in associated dependencies, and JIT/Proxy checks:
-    https://github.com/jjasghar/esxi_health (Ruby)
-    https://github.com/rogerlz/nagios-check-vcenter (Python)
-    https://www.claudiokuenzler.com/nagios-plugins/check_esxi_hardware.php (Python)
-    https://github.com/lgeeklee/pyvinga (Python)

These are less desirable due to having to use JIT/Proxy and the need to deal with Python environment & deps in addition to Ruby.

## Possible Solution
- VMware provides a capable Ruby interface to the vSphere API (https://github.com/vmware/rbvmomi)
- Implement a CLI check plugin that can be used as a JIT/Proxy check using rbvmomi
- Implement an extension using rbvmomi that supports subscription based checks (but not actually requiring sensu-client on a ESXi/vSphere/VCSA node)

## Context
Monitoring of hybrid infrastructure necessitates monitoring of the virtualization infrastructure to include:
 - hypervisor health (cpu, memory, uptime)
 - hypervisor networks
 - data stores
 - etc

## Your Environment
- Sensu 0.26
- vSphere & vCenter 6.5 with VCSA

**Comment by majormoses** [comment]
I don't have the bandwidth to do this any time soon but if someone wants to pick this up I am more than happy to create a repo for them to start working against.

**Comment by majormoses** [comment]
repo created: https://github.com/sensu-plugins/sensu-plugins-vsphere

**Comment by majormoses** [comment]
@portertech now that we have an appropriate repo should we create an issue for this or leave it here?

**Comment by law** [comment]
Also interested in this.  I see the repo has been created, but it looks like a stub plugin instead of something that actually checks, alerts, etc.

**Comment by majormoses** [comment]
@law yup I created the stub hoping that someone would actually work on putting real check/metric scripts, mutators, handlers, etc. I work all in AWS and don't have the time, resources, or expertise to do this on my free time but I am more than happy to help collaborate with you on creating this.

**Comment by law** [comment]
Lol, if you've got no time, resources, or expertise, what could you bring to a collaboration?  Pats on the back and "attaboys"?  :-D

**Comment by tardoe** [comment]
To add something to this thread… this Lib I found might be useful going forward: https://github.com/vmware/govmomi <https://github.com/vmware/govmomi>

- Tim

**Comment by majormoses** [comment]
> Lol, if you've got no time, resources, or expertise, what could you bring to a collaboration? Pats on the back and "attaboys"? :-D

Reviewing code, talking through issues, etc. Lots of engineering effort is around things other than just writing code and sitting down with the VMware API.

**Comment by law** [comment]
Fair enough, I suppose that's what I get for being a smart-alek :-)

**Comment by yuri-zubov** [comment]
the first commit was created https://github.com/sensu-plugins/sensu-plugins-vsphere
I think this issue can be closed

**Comment by mbbroberg** [comment]
Thanks @yuri-zubov! I agree. I'll open an issue to capture some of this post in the README for context to the user.
