### ISSUE TITLE
Request for transfer of the sensu-mssql-plugin ownership.

### ISSUE THREAD

**Issue by devoopes** [sensu-plugins/community#132]
## Transfer Ownership

I queried the current status of the sensu-mssql-plugin on the community slack. After some quick sleuthing @majormoses suggested an issue on this board to have Sensu contact the old maintainer for transfer of repo.

Repo to transfer:
The current repo is 404, https://github.com/sensu-plugins/sensu-plugins-mssql/
Gem File:
 https://rubygems.org/gems/sensu-plugins-mssql/versions/0.0.6

I am also interested in continuing to help as a maintainer of this plugin 👍

**Comment by majormoses** [comment]
Transferring some of my notes from the [chat](https://sensucommunity.slack.com/archives/C3C1D874M/p1567716441012700) in slack

> it looks like this plugin was not maintained by the community. Looking at https://rubygems.org/gems/sensu-plugins-mssql/versions/0.0.6 the author/owner is https://rubygems.org/profiles/maraca

> there is no guarantee that the usernames from github and rubygems match but this would be my first guess: https://github.com/maraca?tab=repositories but I dont see it there either. It's possible they deleted the repo.

> we can email the rubygems owner and see if they would give us ownership so we could reuse the namespace otherwise we will need to rename it to start publishing an updated version.

> here is some quick and dirty how we would grab this:
```
$ cd /tmp/
$ mkdir sensu-plugins-mssql
$ cd sensu-plugins-mssql
$ gem fetch sensu-plugins-mssql
Fetching sensu-plugins-mssql-0.0.6.gem
Downloaded sensu-plugins-mssql-0.0.6
$ gem unpack sensu-plugins-mssql-0.0.6.gem
Unpacked gem: '/tmp/sensu-plugins-mssql/sensu-plugins-mssql-0.0.6'
sensu-plugins-mssql-0.0.6
├── bin
│   └── check-mssql-lag.rb
├── CHANGELOG.md
├── lib
│   ├── sensu-plugins-mssql
│   │   └── version.rb
│   └── sensu-plugins-mssql.rb
└── README.md

3 directories, 5 files
```

> gem files are really nothing more than a tar archive the gem command just obfuscates needing to run lots of unpack commands, dealing with pathing, etc.

**Comment by devoopes** [comment]
Closing issue since there has been no progress and the community is on sensu is closing down and moving to sensu go.
