### ISSUE TITLE
Transfer sensu-plugins-inspec repo

### ISSUE THREAD

**Issue by jspaleta** [sensu-plugins/community#137]
## Transfer Ownership

We would like to transfer the ownership of this plugin to the sensu-plugins organization in hopes of better community support and exposure. I have reviewed [the skeleton plugin](https://github.com/sensu-plugins/sensu-plugins-skel) for best practices.

Repo to transfer:
https://github.com/jspaleta/sensu-plugins-inspec
I am also interested in continuing to help as a maintainer of this plugin 👍

The .travis  config should be setup and ready to go to deploy the ruby gem as well a generating the binary assets.

**Comment by majormoses** [comment]
Please transfer the repo to myself and I will facilitate the transfer to the org as you must be an admin on org to accept a repo into the org. This is outlined here: https://github.com/sensu-plugins/community/blob/master/TRANSFERRING_REPOS.md

**Comment by jspaleta** [comment]
transfer initiated

**Comment by majormoses** [comment]
Transfer complete: https://github.com/sensu-plugins/sensu-plugins-inspec I have mirrored the permisisons. Hit me up if you need anything.
