### ISSUE TITLE
Basic LDAP checks

### ISSUE THREAD

**Issue by jflemer-ndp** [sensu-plugins/community#14]
In https://github.com/sensu-plugins/sensu-plugins-openldap, add a generic check, similar to the generic DNS checks.

```shell
bin/check-ldap.rb --ca-certificate xxx --certificate yyy --encryption start_tls \
  --host 127.0.0.1 --port 686 --bind-dn cn=foo --password abc \
  --base-dn dc=example,dc=com --query '(cn=foo)' --regex-match foo  --scope sub
```

**Comment by majormoses** [comment]
@jflemer-ndp please open this against the actual repo associated for it. This is meant to be a catch all repo for anything not specific to a repo (or requesting a new repo be created).

**Comment by jflemer-ndp** [comment]
Hmm. I'm not sure it belongs to an OpenLDAP plug-in, since I was suggesting a generic plug-in.

**Comment by majormoses** [comment]
I am not sure what you are proposing then. Could you be more specific? What is the check that you would like? What is the purpose? What overlapping use cases are there with existing checks and plugins?

**Comment by jflemer-ndp** [comment]
If I recall, the existing OpenLDAP check looks for openldap specific DNs. Thus the check is only effective for that specific implementation.

Compare to the DNS check, which let's the user specify the name/type to resolve, making it versatile for various conceivable checks (TXT, SRV, public DNS, private DNS).

A generic LDAP check would similarly allow relevant parameters to be user specified. See OP for a notional command line.

Your call if this makes sense as an extension (generic-isation) of the existing check, or a new one. I can resubmit if you like.

**Comment by majormoses** [comment]
I see, after reading this and looking at the current repo I am wondering if we should rename to remove open from the name. My guess is that the original authors intended to simply differentiate from MS AD as the implementation does not seem openldap specific to me from a quick glance. @mattyjones thoughts?

My current thought is rename/copy the current to `sensu-plugins-ldap` and if we need any MS AD specific checks in the future that are not part of the LDAP compliant then it should go in its own repo `sensu-plugins-ms-ad`  Does this make sense to you?

**Comment by majormoses** [comment]
@eheydrick thoughts?

**Comment by eheydrick** [comment]
I think we should create a `sensu-plugins-ldap` for generic LDAP protocol checks. The checks in `sensu-plugins-openldap` are mostly OpenLDAP specific so we should keep it. You could argue that the metrics-ldap check could go in the generic one since that works on more than just OpenLDAP but the syncrepl check is definitely OpenLDAP specific.

**Comment by majormoses** [comment]
I will create a repo for this then.

**Comment by jflemer-ndp** [comment]
This is late, but the current plugin is pretty OpenLDAP specific. Just as an example, see use of `contextCSN`:
https://github.com/sensu-plugins/sensu-plugins-openldap/blob/9b714e1eda5b62b75f0441d56a3a8f5328b3ce3a/bin/check-syncrepl.rb#L138

**Comment by eheydrick** [comment]
@jflemer-ndp Yup, we're going to keep `sensu-plugins-openldap` for OpenLDAP-specific checks like the syncrepl one. Just like we have `sensu-plugins-http` for generic http checks and `sensu-plugins-{nginx|apache}` for server-specific checks.

**Comment by majormoses** [comment]
created: https://github.com/sensu-plugins/sensu-plugins-ldap @eheydrick I will create an issue for you to do all the things I do not have access to.
