### ISSUE TITLE
Please create a new repo 'sensu-plugins-gpg-keys-check'

### ISSUE THREAD

**Issue by adityapahuja** [sensu-plugins/community#15]
Hi Sensu Community Plugins team,

I developed check-gpg-expiry.rb script which checks all public or secret GPG keys' expiry dates and sends appropriate alerts to Sensu client. I also developed check-gpg-expiry-spec.rb script which ensures that the check-gpg-expiry.rb script works properly.

I would like to contribute them to a new repo 'sensu-plugins-gpg-keys-check' in Sensu Community Plugins GitHub. 

Could you please help to create a new repo in Sensu Community Plugins so that I can upload all my files to the repo.

Kind regards,
Aditya

**Comment by GhostLyrics** [comment]
There is already one. https://github.com/sensu-plugins/sensu-plugins-gpg

**Comment by majormoses** [comment]
closing per: https://github.com/sensu-plugins/sensu-plugins-feature-requests/issues/15#issuecomment-279741165
