### ISSUE TITLE
New plugin for working with dovecot

### ISSUE THREAD

**Issue by ushis** [sensu-plugins/community#16]
Hey hey,

i wrote a plugin to collect metrics from dovecot and i am wondering if you are interested in forking it into the sensu-plugins namespace. I would continue maintaining it.

See: https://github.com/ushis/sensu-plugins-dovecot

Cheers, ushi

**Comment by majormoses** [comment]
@ushis sorry for the delay, I have created: https://github.com/sensu-plugins/sensu-plugins-dovecot which has our basic skel (working on making this easier so that there is not so much delay in the future on this). Please feel free to open PRs against it.

**Comment by majormoses** [comment]
@mattyjones ping on permissions

**Comment by eheydrick** [comment]
The repo is all set for rubygems deploys once it's ready for release. @ushis can add Sensu_Plugins  as an owner in Rubygems.

**Comment by ushis** [comment]
@majormoses @eheydrick thanks for setting up the repo.

i am going to migrate the repo this weekend, if i find some time.

**Comment by majormoses** [comment]
your welcome, thank you for contributing.
