### ISSUE TITLE
Becoming a collaborator/maintainer

### ISSUE THREAD

**Issue by majormoses** [sensu-plugins/community#17]
What is the process for becoming a collaborator? I have been contributing where I can via code and review but would like to be able to help with moderating (merging sane requests, releasing, etc) the ever increasing amount of sensu issues.

@mattyjones @portertech

**Comment by mattyjones** [comment]
From the code I have seen and the consistency of the pr's I am good with this. 

@eheydrick

**Comment by sstarcher** [comment]
From what I have seen of @majormoses I'm in support.  He has been very active.

**Comment by mattyjones** [comment]
good enough for me as well. Invite has been sent as well as added to the team that gives commit-bit. @majormoses

**Comment by majormoses** [comment]
@mattyjones is there a bot that does our gem releases or do I need to be added individually to the gems in order to release?

**Comment by majormoses** [comment]
nvm I found the answer: https://github.com/sensu-plugins/documentation/blob/master/infra/b_and_r.md#build-and-release-pipeline

**Comment by eheydrick** [comment]
@majormoses That's the old process not used anymore. The docs need to be updated but basically the new process is you create a github release and travis runs a gem deploy. I use the hub command: `hub release create x.y.z`. Other things about releases: 

1. Make sure the CHANGELOG reflects all the changes. The Unreleased link in the CHANGELOG gives you a nice diff.
2. Make sure the README is updated as necessary.
3. Follow semver. Breaking changes are a major. Any new checks are a minor. Fixes to existing checks are a patch.
4. Make sure the gem is actually uploaded to rubygems. It's rare but I've seen times when it doesn't upload for whatever reason.
5. travis will only deploy if the build is passing so make sure master is building before cutting a release.

**Comment by majormoses** [comment]
@eheydrick thanks I have created an issue and assigned it to myself for updating the documentation after I have tried it out.
