### ISSUE TITLE
Plugin Repo Skel

### ISSUE THREAD

**Issue by majormoses** [sensu-plugins/community#19]
Is there a skeleton repo that can be copied from when creating a new repo?

@mattyjones @eheydrick

**Comment by eheydrick** [comment]
Not really. There was a effort to generate new repos with rake tasks but it's out of date at this point. We should create a repo based on one of the up to date repos like [sensu-plugins-kubernetes](https://github.com/sensu-plugins/sensu-plugins-kubernetes).

**Comment by majormoses** [comment]
I created a repo for it: https://github.com/sensu-plugins/sensu-plugins-skel when I have some time I will start working on putting it together.

**Comment by eheydrick** [comment]
👍
