### ISSUE TITLE
Transfer ownership of plugin sensu-plugins-jolokia to sensu-plugins organization

### ISSUE THREAD

**Issue by smbambling** [sensu-plugins/community#22]
We would like to transfer the ownership of this plugin to the sensu-plugins organization in hopes of better community support and exposure.

Per Slack convo I'll compare against https://github.com/sensu-plugins/sensu-plugins-skel to prep it for transfer 

https://github.com/arineng/sensu-plugins-jolokia

**Comment by majormoses** [comment]
Once you are ready follow the instructions here: https://help.github.com/articles/transferring-a-repository-owned-by-your-personal-account/#transferring-to-an-organization and I can transfer it over.

**Comment by majormoses** [comment]
transferred: https://github.com/sensu-plugins/sensu-plugins-jolokia

**Comment by majormoses** [comment]
closed per https://github.com/sensu-plugins/sensu-plugins-jolokia/pull/1
