### ISSUE TITLE
Transfer ownership of plugin sensu-plugins-switchvox to sensu-plugins organization

### ISSUE THREAD

**Issue by smbambling** [sensu-plugins/community#23]
We would like to transfer the ownership of this plugin to the sensu-plugins organization in hopes of better community support and exposure.

Per Slack convo I'll compare against https://github.com/sensu-plugins/sensu-plugins-skel to prep it for transfer 

https://github.com/arineng/sensu-plugins-switchvox

**Comment by majormoses** [comment]
Once you are ready follow the instructions here: https://help.github.com/articles/transferring-a-repository-owned-by-your-personal-account/#transferring-to-an-organization and I can transfer it over.

**Comment by majormoses** [comment]
https://github.com/sensu-plugins/sensu-plugins-switchvox

**Comment by eheydrick** [comment]
The repo has been updated to the latest skel standards and released as [1.0.0](https://rubygems.org/gems/sensu-plugins-switchvox/versions/1.0.0). Thanks for contributing the plugin, @smbambling!
