### ISSUE TITLE
Kubernetes Sensu Plugins Repo

### ISSUE THREAD

**Issue by nyxcharon** [sensu-plugins/community#3]
Hello,

@kelcecil, @jmccarty3 and myself have developed a few Sensu plugins and a handler for Kubernetes and we were wanting to get a repo made for it so others can find it easily.  The repo is currently located here:
https://github.com/nyxcharon/sensu-plugins-kubernetes

These checks have been in use in a production environment since the beginning of august or so.
Let me know if you need me to do anything or need any more information from me.

**Comment by sstarcher** [comment]
+1

**Comment by kelcecil** [comment]
I love it when a plan comes together!

**Comment by analytically** [comment]
@mattyjones

**Comment by sstarcher** [comment]
Any chance we could get this in?

**Comment by eheydrick** [comment]
Hey sorry for the delay, I created https://github.com/sensu-plugins/sensu-plugins-kubernetes.

**Comment by nyxcharon** [comment]
@eheydrick Do you just want me to submit a PR against that repo or what would you prefer?

**Comment by eheydrick** [comment]
@nyxcharon I've added boilerplate to the repo. For now go ahead and send a PR.

**Comment by nyxcharon** [comment]
Since the repo has been made and I have PR open for the new repo, I'm going to go ahead and close this. Link for the PR: https://github.com/sensu-plugins/sensu-plugins-kubernetes/pull/1
