### ISSUE TITLE
Transfer ownership of plugin sensu-plugins-signifai to sensu-plugins organization

### ISSUE THREAD

**Issue by zcarlson-signifai** [sensu-plugins/community#30]
## Transfer Ownership

We would like to transfer the ownership of this plugin to the sensu-plugins organization in hopes of better community support and exposure. I have reviewed [the skeleton plugin](https://github.com/sensu-plugins/sensu-plugins-skel) for best practices.

Repo to transfer: https://github.com/signifai/sensu-plugins-signifai/

I am also interested in continuing to help as a maintainer of this plugin 👍

**Comment by majormoses** [comment]
@zcarlson-signifai awesome, I can help facilitate that and am more than happy to add you as a collaborator on the plugin. If you can follow the instructions here: https://help.github.com/articles/transferring-a-repository-owned-by-your-personal-account/ to transfer to the sensu-plugins org I can accept it and start working on getting stuff like travis setup.

**Comment by zcarlson-signifai** [comment]
When attempting to transfer ownership of the sensu-plugins-signifai repo to the sensu-plugins organization, I am getting the error "You don’t have the permission to create repositories on sensu-plugins."

**Comment by majormoses** [comment]
Ok it seems you need to transfer it to me and I can transfer it to org, sorry first time I am doing this and I will update the documentation on this go through this as I would like it to be as easy as possible in the future.

**Comment by zcarlson-signifai** [comment]
I have initiated the transfer to @majormoses .

(Note also that if the repo is part of an organization, you may need to transfer it to your own user first before transferring again)

**Comment by majormoses** [comment]
repo transfered and you still have write access: https://github.com/sensu-plugins/sensu-plugins-signifai

**Comment by majormoses** [comment]
We will start bringing it more inline with our standard setup which can be found in our skel: https://github.com/sensu-plugins/sensu-plugins-skel

**Comment by majormoses** [comment]
I have ensured that it is transferred and deploys are setup correctly now.
