### ISSUE TITLE
Transfer Ownership of sensu-plugins-dcos

### ISSUE THREAD

**Issue by luisdavim** [sensu-plugins/community#33]
## Transfer Ownership

We would like to transfer the ownership of this plugin to the sensu-plugins organization in hopes of better community support and exposure. I have reviewed [the skeleton plugin](https://github.com/sensu-plugins/sensu-plugins-skel) for best practices.

Repo to transfer:
https://github.com/PTC-Global/sensu-plugins-dcos

I am also interested in continuing to help as a maintainer of this plugin 👍

**Comment by majormoses** [comment]
So you need to transfer the repo to me per: https://help.github.com/articles/transferring-a-repository-owned-by-your-personal-account and then I will transfer it over to the org, do the travis + rubygems setup, etc.
