### ISSUE TITLE
Move to Slack as primary communication platform

### ISSUE THREAD

**Issue by mbbroberg** [sensu-plugins/community#34]
The maintainers of Sensu Plugins and contributors from Sensu Inc have discussed adoption of a more user-friendly and easily accessible real-time communication platform for years. Since the group's decision to [go into Maintenance Mode](https://blog.sensuapp.org/community-maintenance-mode-d109e75bcbc4), we have moved to building out a Sensu Community Slack team that will meet these requirements.

## Why 
For many, Slack is the app where they participate in multiple communities - both open source and proprietary - on a regular basis. It also doesn't require you to be online to receive a response. The near universal adoption along with the ease of response are the two main reasons to make this move.

## When 
Effective immediately, we will recommend people join our Slack team by invite or through this landing page at [slack.sensu-plugins.io](http://sensucommunityslack.herokuapp.com/). We will officially focus our developer/user real-time communication to Slack as of [Sensu Summit on August 15, 2017](https://sensuapp.org/summit).

## Steps 
Maintainers and some contributors have already joined the new Slack and began to build it into the multi-channel location they'd like it to be. Beyond that, we will do achieve the following before closing this issue: 

- [x] Adjust Sensu, Sensu Plugin and Sensu Extension organizations to point users to Slack
- [x] Share this issue on IRC so others can note the move

## Notes 
* Active maintainers of Sensu Plugins will have admin rights over the Sensu Community Slack. 
* We've considered costs associated with Slack and chosen to allow Sensu Inc to pay for the service, giving the org key features we will use
* Also discussing costs, we considered how many pay for persistent IRC sessions or pay for server time to run an IRC service and how this choice takes that burden off of the community member

**Comment by majormoses** [comment]
I have made an announcement in slack today, we should probably try to do 1 a day or something for a while, @mbbroberg unless you feel differently

**Comment by mbbroberg** [comment]
Note that anyone who wants to continue to use an IRC app instead can login using the IRC gateway. Once they create an account, follow the directions here: https://sensucommunity.slack.com/account/gateways

**Comment by mbbroberg** [comment]
I've adjusted both GitHub organizations to point to Slack. Checking that box ✅

**Comment by majormoses** [comment]
@mbbroberg anything else we want to do to call this closed?

**Comment by mbbroberg** [comment]
No, I think we nailed it! 

![high-five](https://user-images.githubusercontent.com/1744971/29684931-9851d4de-88c8-11e7-8b8f-aac4ffa8f238.gif)
