### ISSUE TITLE
Becoming a collaborator/maintainer

### ISSUE THREAD

**Issue by luisdavim** [sensu-plugins/community#37]
Hi,

I have been contributing with some PRs and code reviews but would like to be able to help with moderating (merging sane requests, releasing, etc) specially on the sensu-extensions org that seems to be lacking maintainers.

@mattyjones @portertech @majormoses

**Comment by majormoses** [comment]
I am :+1:  need one more and I am good to start the process.

**Comment by eheydrick** [comment]
👍

**Comment by majormoses** [comment]
I have sent the invitation, I will reach out and explain some things about how things work on the plugins projects since we are gonna be moving a lot of the good process from plugins to extensions.

**Comment by majormoses** [comment]
confirmed that he has accepted, considering this done.
