### ISSUE TITLE
Transfer of ownership of sensu-plugins-pdns to community

### ISSUE THREAD

**Issue by haashah** [sensu-plugins/community#39]
We would like to transfer the ownership of this plugin to the sensu-plugins organization in hopes of better community support and exposure. I have reviewed [the skeleton plugin](https://github.com/sensu-plugins/sensu-plugins-skel) for best practices.

Repo to transfer:

https://github.com/haashah/sensu-plugins-pdns

I am also interested in continuing to help as a maintainer of this plugin 👍

**Comment by majormoses** [comment]
Please transfer the repo to me and I will facilitate the transfer per: https://help.github.com/articles/transferring-a-repository-owned-by-your-personal-account and I will transfer it to the org.

**Comment by haashah** [comment]
repo has been transferred

**Comment by majormoses** [comment]
Hmm, I have not seen the email come in. I will check in the morning, If I don't see it I will message back. Hit me up in the [community slack](https://slack.sensu.io)

**Comment by majormoses** [comment]
Ok I found it buried but unfortunately it is expired can you restart the process?
![image](https://user-images.githubusercontent.com/3145127/29468566-a7d15228-83f9-11e7-9c50-c1878f2c4a39.png)

**Comment by haashah** [comment]
restarted the transfer process once again. Hope you have the email

**Comment by majormoses** [comment]
Sorry I was not watching this on the weekend. let's try this on monday. Really sorry about this. Might be worth sending me a message on slack when you initiate it.

**Comment by haashah** [comment]
Okey dokey

**Comment by majormoses** [comment]
@eheydrick sorrry for personal reasons I am not gonna be available for a few days can you please facilitate this?

**Comment by haashah** [comment]
@eheydrick  should I transfer the repo to you?

**Comment by eheydrick** [comment]
@haashah yes go ahead and transfer to me and I'll transfer into the org.

**Comment by eheydrick** [comment]
Repo has been transferred to https://github.com/sensu-plugins/sensu-plugins-pdns. I will get it setup to release as a rubygem.

**Comment by eheydrick** [comment]
Opened https://github.com/sensu-plugins/sensu-plugins-pdns/issues/1 to track prepping the repo for release.
