### ISSUE TITLE
Mailgun plugin repo

### ISSUE THREAD

**Issue by brendangibat** [sensu-plugins/community#4]
Hello,

I've made a sensu plugins repo for checks and metrics on Mailgun, and would like this to be made available to others. The repo is located at:

https://github.com/brendangibat/sensu-plugins-mailgun

Let me know what you need to get the repo in to sensu-plugins shape.

Thanks!

@sstarcher

**Comment by eheydrick** [comment]
Hey, sorry for the delay. I created https://github.com/sensu-plugins/sensu-plugins-mailgun. It'll need boilerplate added. Let us know if you need any help with anything. Check out the docs at http://sensu-plugins.io/docs/developer_guidelines.html for the format you'll want to follow. Thanks for contributing!

**Comment by mattyjones** [comment]
@brendangibat ^^

**Comment by brendangibat** [comment]
Great, thanks! I'm starting to update the repo to follow the guidelines.
