### ISSUE TITLE
new repo: sensu-plugins-vault

### ISSUE THREAD

**Issue by jaxxstorm** [sensu-plugins/community#43]
## New Repo

We currently have sensu-plugins-consul. I'd like to be able to contribute my sensu plugin for hashicorp vault

Repo to create: sensu-plugins-vault

I am also interested in continuing to help as a maintainer of this plugin 👍

**Comment by majormoses** [comment]
created: https://github.com/sensu-plugins/sensu-plugins-vault we just need to start pushing stuff from the skel here: https://github.com/sensu-plugins/sensu-plugins-skel

**Comment by majormoses** [comment]
I have made you an external collaborator as well.

**Comment by jaxxstorm** [comment]
Will get this sorted, thanks!

**Comment by petems** [comment]
@jaxxstorm Hey Lee! Did you get a chance to push to the repo with the Vault plugins? I see it's still empty at the repo: https://github.com/sensu-plugins/sensu-plugins-vault
