### ISSUE TITLE
Create Best Practices Document for testing

### ISSUE THREAD

**Issue by mbbroberg** [sensu-plugins/community#46]
_migrating from https://github.com/sensu/sensu-summit-notes/issues/9_

Basically write up how to write good tests and how the tests work:
- [x] types of testing and their effectiveness
- [x] testing platforms (start with linux, slowly add bsd, etc some like AIX will likely never be a thing
- [x] testing tools: `travis`, `test-kitchen`, `kitchen-docker`,`(server|in)pec`, `rake`, etc

**Comment by mbbroberg** [comment]
I think this should be considered blocked until #58 lands. Thoughts?

**Comment by majormoses** [comment]
Getting the thoughts written down is the hard part so if someone wants to start thinking about all the things that needed to be discussed and come up with an outline I see no reason to block them. We can always move it somewhere else or update the format later.

**Comment by mbbroberg** [comment]
Sgtm. Will leave it as a priority and raise it to the community regularly until someone else has free time. It's a great place for someone who wants to be a maintainer to hop in.

**Comment by mattyjones** [comment]
Any traction on this. My head has been up in RSpec for some time now w/ Terraform. It would take much for me to swap some of that to sensu-plugins. I would either do it as a gist in the open here or a GDoc?

**Comment by majormoses** [comment]
Sorta? I have a couple of blog articles that will be coming out in the next week or two after being reviewed. We are looking to basically use `test-kitchen`, `kitchen-docker`, and `serverspec`. I have rolled it out to a few of the repos a good example is dcos. Once those blog posts come out I think I can sit down and create a more formal document. One of the reasons I like `serverspec` is that it is really just an extension on `rspec` and is a bit more "sysadmin" friendly. One of the many benefits of doing it in docker containers is that it forces us to show what are the required dependencies to install a check and use it are. I opted for not using `inspec` as we are not really testing chef specific stuff and I wanted something a bit more vendor neutral.

**Comment by majormoses** [comment]
I will compile a list of PRs to link here for the mean time to show what it would look like:
- https://github.com/sensu-plugins/sensu-plugins-postgres/pull/43
- https://github.com/sensu-plugins/sensu-plugins-redis/pull/49
- https://github.com/sensu-plugins/sensu-plugins-dcos/pull/10
- https://github.com/sensu-plugins/sensu-plugins-dns/pull/26/commits/bb29bccc73604d6500a29e4512a8dc8ed6a9bb47
- https://github.com/sensu-plugins/sensu-plugins-load-checks/pull/17
- https://github.com/sensu-plugins/sensu-plugins-beanstalk/pull/7

There are others that have the skel in place but not actual tests. I really need to add the testing stuff to skel...

**Comment by majormoses** [comment]
I have been keeping track here: https://github.com/sensu-plugins/community/issues/41

**Comment by mattyjones** [comment]
I second the use of ServerSpec and docker along with test-kitchen.Test-kitchen is fast becoming a standard tool in the community. Heck I am using it with terraform ;)

**Comment by majormoses** [comment]
They are live now:
- https://blog.sensuapp.org/our-approach-to-testing-sensu-plugins-869260eba94c
- https://blog.sensuapp.org/writing-sensu-plugin-tests-with-test-kitchen-and-serverspec-b646d2eeee51

**Comment by mbbroberg** [comment]
I believe the posts coming out cover our bases. Leaving this open until we decide where this information lands inside our community.

**Comment by majormoses** [comment]
I added the testing bits to the skel in https://github.com/sensu-plugins/sensu-plugins-skel/pull/10

**Comment by mbbroberg** [comment]
Sounds like the right place for it to live. Closing!
