### ISSUE TITLE
Transfer ownership of plugin sensu-plugins-systemd to to sensu-plugins organization

### ISSUE THREAD

**Issue by mickfeech** [sensu-plugins/community#48]
## Transfer Ownership

We would like to transfer the ownership of this plugin to the sensu-plugins organization in hopes of better community support and exposure. I have reviewed [the skeleton plugin](https://github.com/sensu-plugins/sensu-plugins-skel) for best practices.

Repo to transfer:  https://github.com/mickfeech/sensu-plugins-systemd

I am also interested in continuing to help as a maintainer of this plugin 👍

**Comment by majormoses** [comment]
please transfer the repo to me `@majormoses` and I will transfer it to the org. After that I will setup automated deploys and try to bring it as close as possible to our standard things (like rubocop, rake, etc)

**Comment by mickfeech** [comment]
Transfer initiated.

**Comment by majormoses** [comment]
created: https://github.com/sensu-plugins/sensu-plugins-systemd
