### ISSUE TITLE
Move flapjack handler over

### ISSUE THREAD

**Issue by CVTJNII** [sensu-plugins/community#5]
Currently the Flapjack handler is still in the deprecated repo: https://github.com/sensu/sensu-community-plugins/blob/master/extensions/handlers/flapjack.rb  I'm assuming it was not moved to favor the built in Sensu Flapjack handler, however per https://sensuapp.org/docs/latest/enterprise-built-in-handlers#flapjack built-in Flapjack appears to be an enterprise only feature.  Please bring the external Flapjack handler back into the fold.  Thanks.

**Comment by CVTJNII** [comment]
So, with the closing of sensu/sensu-community-plugins this handler has floated off into the aether.  Is there any official support for Flapjack for non-Enterprise users?

**Comment by tdi** [comment]
+1

**Comment by zoran** [comment]
+1

**Comment by eheydrick** [comment]
We will find a better home for the community version of the flapjack handler. For now it's still available at https://github.com/sensu/sensu-community-plugins/blob/e58c1f3ce39c6c0ca271fadd470c04362e92b190/extensions/handlers/flapjack.rb

**Comment by CVTJNII** [comment]
This extension is now broken against Sensu 0.23: https://github.com/sensu/sensu/issues/1224.  It really needs a home.

EDIT: extension not plugin

**Comment by calebhailey** [comment]
So, extensions and plugins are two very different things. A poorly written handler plugin is far less capable of compromising a Sensu process than an extension (which run inside the Sensu process). The [current issue with the Flapjack handler extension](https://github.com/sensu/sensu/issues/1224) is a great example of this - because it is an extension it's causing the `sensu-server` process to die rather than just resulting in a logged error in the `sensu-server.log` file. 

I think this is one of the reasons we've been hesitant to suggest that extensions should live in the new https://github.com/sensu-plugins org, but dragging our feet about making a decision obviously isn't helping anyone. We need to find a home for community extensions to facilitate ongoing maintenance and discussion. 

I'm super hesitant about mixing extensions and plugins in the sensu-plugins org, because new users need to understand the clear distinction between plugins and extensions (this is also on the top of our list of ongoing documentation improvements, FWIW). Does it make sense to create YAGO (Yet Another GitHub Org) for sensu-extensions? Or would a new repo under the Sensu org suffice? Discuss!

/cc @CVTJNII @portertech

**Comment by NiGame** [comment]
+1

**Comment by compuguy** [comment]
Any updates, this handeler is still broken with the latest version of sensu (0.25.3).

**Comment by mdzidic** [comment]
Any updates regarding Flapjack handler? Latest working Sensu version 0.22

**Comment by brianczapiga** [comment]
Disclaimer: This code is hacked together from portions of Flapjack, Sensu, and the original plugin. Attribution was given where possible.

https://github.com/brianczapiga/sensu-flapjack

**Comment by psyhomb** [comment]
Does anyone did some tests regarding new Flapjack handler?

Does the handler now work with new Sensu and with new Flapjack version (2.0.0), I see from the code that answer to this question is probably positive but I was wondering is there anyone out there who can give hands-on confirmation? Thx

**Comment by brianczapiga** [comment]
The pipe handler that I hacked together works with 2.0.0 and the latest version of sensu. The latest flapjack 2.0.0 lacks some features that were available in 1.6.0, like being able to modify contacts using the UI (must be done via API)

I would recommend staying with 1.6.0.

**Comment by psyhomb** [comment]
Thanks for the quick answer.

I'm using Flapjack API anyhow, even on version 1.6.0, for contacts and notification rules creation...

Yeah I'm planning to stay with version 1.6.0 for some time more but IMHO this version has one big drawback (solved in version 2.0.0) it doesn't have check deletion function, so basically you can't delete any stale check, rather you can disable it which will cause for check to stay (forever) in the Redis and it would effectively only be hidden from the WebUI. These stale (disabled) checks will dramatically increase Flapjack API response time over time.

**Comment by psyhomb** [comment]
@brianczapiga one more question, why you didn't use subclass `Sensu::Handler` in your code?

```
require 'sensu-handler'
class Flapjack < Sensu::Handler
  <your code here>
end
```

**Comment by brianczapiga** [comment]
I'm not sure, I think I had some gem dependency issue at the time and not being a ruby pro, I opted to work around the issue instead of correct it. It would definitely make sense to use the sensu handler gem.

**Comment by eoly** [comment]
I hacked this together today after running into a problem with the Flapjack extension after we upgraded to Sensu 0.25.x.

https://gist.github.com/eoly/66f36b824bee93b4105db1cacea62c37

**Comment by psyhomb** [comment]
I'm encountering an issue with this handler, probably something related to `Bridge` class inheritance, do you guys now how could I resolve this one?

`{"timestamp":"2016-08-12T17:37:20.643563+0200","level":"error","message":"unknown handler","handler_name":"flapjack"}`

**Comment by eoly** [comment]
The Flapjack extension I posted is not a handler. So if you have any checks defined with the flapjack handler you will get that error. The bridge extension will stream all events to flapjack. No need to use a handler in your checks definitions. The bridge method is how Sensu enterprise handles the flapjack integration.

**Comment by eoly** [comment]
The flapjack.rb file should be written to /etc/sensu/extensions/flapjack.rb.

Then you should have the configuration in /etc/sensu/conf.d/extensions/flapjack.json. With contents similar to.

```
{
  "flapjack": {
    "host": "flapjack.example.com",
    "port": "6379",
    "db": "0"
  }
}
```

**Comment by psyhomb** [comment]
That totally makes sense now or makes sensu :), I have configuration files in place and everything else needed but I didn't know this part about bridge method, big thanks for clarification.

**Comment by psyhomb** [comment]
I'm going to run some tests now, will post the update after that...

**Comment by psyhomb** [comment]
I've added some additional features and now we have flapjack extension that supports:
- New sensu 0.25 (thanks to @eoly)
- Starting from version 0.23 Sensu services can now be configured to query one or more instances of Redis Sentinel for a Redis master, and cause we're requiring the same 'sensu/redis' gem for Flapjack extension, we can use this feature here as well
- Activation/Deactivation through extension's configuration file `"enabled": true|false`
- Activation/Deactivation of flapjack extension on check level `"flapjack_enabled": true|false`
- Added support for `initial_failure_delay` and `repeat_failure_delay` directives in both flapjack (global) and check (local) configuration 
- Added support for Flapjack v2.0 `"flapjack_version": 1|2`
- Added support for nagios output format `TEXT | PERFDATA` (requires `"output_type": "nagios"` in check definition)

``` json
{
   "flapjack": {
      "host": "localhost",
      "port": 6379,
      "db": "0",
      "initial_failure_delay": 30,
      "repeat_failure_delay": 60,
      "flapjack_version": 1,
      "enabled": true
   }
}
```

``` json
{
   "checks": {
     "check_disk_usage": {
       "command": "check-disk-usage.rb",
       "subscribers": [
         "test"
       ],
       "interval": 60,
       "output_type": "nagios",
       "initial_failure_delay": 120,
       "repeat_failure_delay": 300,
       "flapjack_enabled": true
    }
  }
}
```

https://github.com/psyhomb/sensu-extension-flapjack/blob/master/flapjack.rb

**Comment by portertech** [comment]
Thank you @psyhomb :+1:

**Comment by atul86244** [comment]
With sensu 1.2.1 I kept getting the below error:

```{"timestamp":"2018-03-16T10:08:37.674235+0000","level":"error","message":"unknown handler","handler_name":"flapjack"}```
```{"timestamp":"2018-03-16T10:08:47.675897+0000","level":"error","message":"unknown handler","handler_name":"flapjack"}```

 so had to modify the extension with a small change to get it working for sensu 1.2.1
 
https://github.com/atul86244/flapjack/blob/master/flapjack.rb

**Comment by psyhomb** [comment]
@atul86244 modifications are already made please read the full thread
https://github.com/sensu-plugins/community/issues/5#issuecomment-239481722

**Comment by atul86244** [comment]
@psyhomb  got it, thanks.

**Comment by majormoses** [comment]
I'd like to re-open this and work on transfering https://github.com/psyhomb/sensu-extension-flapjack to the https://github.com/sensu-extensions org so there is better visibility on this. @psyhomb if you can transfer the repo to me I can transfer it to the org. Then we can collaborate on making it a bit better for example I'd like to see it published as a gem. Of course we would invite you to continue maintaining it.
