### ISSUE TITLE
Guidelines for contribution

### ISSUE THREAD

**Issue by mbbroberg** [sensu-plugins/community#52]
There are a few universal practices that are worth documenting in this repository and possibly syndicating into all plugins within the organization: 

- [x] Use of labels on issues/PRs 
- [x] PR policies (style guides, staleness before closing)

I think it will be helpful to start with a document in this repository and then think about the right amount of information to sync to repos in the form of a CONTRIBUTING.md file.

**Comment by majormoses** [comment]
@mbbroberg other than going more into labels is there anything else you think that we need to address that is not part of https://github.com/sensu-plugins/community/blob/master/PULL_REQUEST_PROCESS.md?

**Comment by mbbroberg** [comment]
@majormoses no you tackled it perfectly! Closing.
