### ISSUE TITLE
Transfer ownership of plugin sensu-plugins-stackstorm to sensu-plugins organization

### ISSUE THREAD

**Issue by userlocalhost** [sensu-plugins/community#53]
## Transfer Ownership

We would like to transfer the ownership of this plugin to the sensu-plugins organization in hopes of better community support and exposure. I have reviewed [the skeleton plugin](https://github.com/sensu-plugins/sensu-plugins-skel) for best practices.

Repo to transfer: https://github.com/userlocalhost/sensu-plugins-stackstorm

I am also interested in continuing to help as a maintainer of this plugin 👍

If that's OK, I'll transfer the ownership of it to an owner (@majormoses) of this organization according to the [instruction](https://help.github.com/articles/transferring-a-repository-owned-by-your-personal-account/).

**Comment by majormoses** [comment]
@userlocalhost you can transfer it to me and I can transfer it into the org. I also see https://rubygems.org/gems/sensu-plugins-stackstorm so we will also want to be able to automate the deploys can you please also run `gem owner sensu-plugins-stackstorm -a sensu-plugin@sensu-plugins.io`?

**Comment by userlocalhost** [comment]
Thank you for your reply and approval, @majormoses!

I made a request to transfer the ownership of that repository to you, and added `Sensu_Plugins` to the gem of it as an owner.

**Comment by majormoses** [comment]
transfered: https://github.com/sensu-plugins/sensu-plugins-stackstorm

**Comment by majormoses** [comment]
I will consider this done and will work on the terraforn, slack, travis, rubygems, etc this weekend.

**Comment by userlocalhost** [comment]
Thank you very much for your work!
