### ISSUE TITLE
Transfer ownership of plugin sensu-plugins-microsoft-teams to sensu-plugins organization

### ISSUE THREAD

**Issue by tuxpower** [sensu-plugins/community#56]
I would like to transfer the ownership of this plugin to the sensu-plugins organization in hopes of better community support and exposure. I have reviewed [the skeleton plugin](https://github.com/sensu-plugins/sensu-plugins-skel) for best practices.

Repo to transfer:
https://github.com/tuxpower/sensu-plugins-microsoft-teams

I am also interested in continuing to help as a maintainer of this plugin 👍

**Comment by majormoses** [comment]
You can transfer the repo to me and I can transfer it to the community, I took a very quick look and before you transfer could you please remove the `.swp` file?

**Comment by tuxpower** [comment]
Hi @majormoses I've just transferred this repo to you.

**Comment by majormoses** [comment]
transfered: https://github.com/sensu-plugins/sensu-plugins-microsoft-teams

**Comment by majormoses** [comment]
imprted into terraform. I will open up issues for the rest of the standard stuff like changelogs, ci, etc.
