### ISSUE TITLE
Transfer zfs sensu-plugins-zfs

### ISSUE THREAD

**Issue by blacksails** [sensu-plugins/community#57]
## Transfer Ownership

I would like to transfer the ownership of this plugin to the sensu-plugins organization in hopes of better community support and exposure. I have reviewed [the skeleton plugin](https://github.com/sensu-plugins/sensu-plugins-skel) for best practices.

Repo to transfer: https://github.com/blacksails/sensu-plugins-zfs

**Comment by majormoses** [comment]
https://github.com/blacksails/sensu-plugins-zfs/issues/4

**Comment by majormoses** [comment]
I would be more than happy to facilitate  this, please read through here: https://github.com/sensu-plugins/community/blob/master/TRANSFERRING_REPOS.md for instructions on how to transfer the repo to me and I will transfer it to the organization, setup ci + cd, bring things more inline with community plugins, etc

**Comment by majormoses** [comment]
repo transferred: https://github.com/sensu-plugins/sensu-plugins-zfs

**Comment by blacksails** [comment]
What is it that I need to do on rubygems?

**Comment by majormoses** [comment]
run the command in `#7` here: https://github.com/sensu-plugins/community/blob/master/TRANSFERRING_REPOS.md adjusted for repo name...

**Comment by majormoses** [comment]
I will work on then getting it setup with terraform, travis, etc. before we consider this "done".

**Comment by blacksails** [comment]
@majormoses FYI I have setup the ownership in rubygems.

**Comment by majormoses** [comment]
I have imported into terraform. I will open an issue in the repo to do the rest of the setup.
