### ISSUE TITLE
Transfer sensu-plugin-python to sensu-plugins org

### ISSUE THREAD

**Issue by barryorourke** [sensu-plugins/community#59]
## Transfer Ownership

Following on from our discussions on slack, we would like to move the sensu-plugin-python repo over from sensu org to sensu-plugins org.

Repo to transfer: https://github.com/sensu/sensu-plugin-python

I am also interested in continuing to help as a maintainer of this plugin as is @luisdavim 👍

**Comment by majormoses** [comment]
I am not an admin on that org so I need someone to transfer it to me. Here is the doc how for whoever has the appropriate permissions: https://github.com/sensu-plugins/community/blob/master/TRANSFERRING_REPOS.md If they are also an admin in the plugins org they can actually transfer it directly.

**Comment by barryorourke** [comment]
@mbbroberg I see you are an admin on both orgs, could you do the transfer for us please?

**Comment by portertech** [comment]
@mbbroberg 👍

**Comment by mbbroberg** [comment]
@barryorourke on it!

**Comment by mbbroberg** [comment]
Done! 

https://github.com/sensu-plugins/sensu-plugin-python

**Comment by majormoses** [comment]
I will close this out when I import this into the terraform state.

**Comment by mbbroberg** [comment]
Good call - thanks @majormoses

**Comment by majormoses** [comment]
I have imported it into terraform state file (pr to come shortly).
