### ISSUE TITLE
Feedback on new GitHub Labels

### ISSUE THREAD

**Issue by mbbroberg** [sensu-plugins/community#63]
> _**NOTE:** This issue will be left open for some time in order to aggregate feedback, recommendations or advice. The decision on labels is ultimately at the discretion of the maintainer team._

The Sensu Plugin maintainers recently released a set of more granular labels and configured them on all Plugin repositories. They are namespaced to organize them into easily-found buckets as maintainers scroll through: 

- Type - identify the type of Issue (specifically for issues)
- Status - provides a state or indicator (used for PRs or Issues)
- Area - help classify the type of Sensu feature in use
- Platform - classify the operating system
- Impact - mostly for PRs to indicate breaking changes
- Priority - to ... prioritize 😄 

A great example of these colorful and informative labels can be found here: https://github.com/sensu-plugins/sensu-plugins-aws/labels

<img width="889" alt="screen shot 2017-10-11 at 10 33 46 am" src="https://user-images.githubusercontent.com/1744971/31456799-b360bea8-ae6f-11e7-8f7c-b09a55141f79.png">

I'm curious to hear from everyone on whether people see labels that could be more helpful, or consolidated or removed. General thoughts on your experience interacting with labels will also be appreciated. Thanks!

**Comment by majormoses** [comment]
I am thinking we should make `Status: Help Wanted` to be `Help Wanted` or we should maybe add the other tag?

![image](https://user-images.githubusercontent.com/3145127/31801480-55e5a308-b4fd-11e7-8b20-535d4add3cf8.png)

**Comment by mbbroberg** [comment]
@majormoses yeah, GH gave us a curveball on this one. That's a cool new feature we should totally take advantage of. So a few thoughts: 

*  Migrate `Status: Help Wanted` to be `Help Wanted`
* Add `Good First Issue` if we think we have sufficiently easy first contributions on a project (is that common?? I haven't seen a ton of it) 
* Consider removing `Status: Claimed` since behaviorally `Status: In Progress` seems to make more sense for work in progress and we can assign issues when they are "Claimed" (exception: assignment doesn't work for non-org members) or we simply stick to In Progress as a the indicator

Thoughts @majormoses ?

**Comment by majormoses** [comment]
- For migration of `Help Wanted` we probably want to first do a pass on all plugins that have this label and delete it to avoid duplication.
- `good first issue` is not one I have actually seen much though I have on a few projects, certainly not widespread. I have seen variations such as `easy`, `low hanging`, etc use more often.
- I'm good with either and don't really have a strong opinion one way or another but I do think we should pick one. While they are technically different there is such a minor difference that it's of limited value.

**Comment by majormoses** [comment]
I think there are a handful of examples where people have claimed but not started work. I am guessing after I while we should just remove the claimed/"in progress"

**Comment by mbbroberg** [comment]
RE migration, running terraform wouldn't do a renaming, right?

If not, [repo_man](https://github.com/mbbroberg/repo_man) is the best tool for remapping and preserving tagging. I know it's harder to import if we do that, but it's important not to lose the context too. I'd love to pair with you on this one. 

RE first good, let's make the call to not use if it we don't like the language and don't see enough of a need.

RE Claimed, let's delete it and stick to In Progress since that's working.

**Comment by majormoses** [comment]
It will certainly do the naming that being said there are already tags with that so we should clean up the ones that are not managed by terraform and then it will be easy to rename.

**Comment by mbbroberg** [comment]
> the ones that are not managed by terraform

Is there a quick way to know what isn't managed by TF? I guess I still get stuck at times on what's in the state and what is yet to be managed given all our bits. 

I'd also like to learn from fixing this, so if we can either pair in real-time or if you can record your screen when addressing it or remind me of the workflow to do so and I will then that'd be super dope 👌.

**Comment by mbbroberg** [comment]
This has been really helpful. Now it's time to finish up the TF work! Adding a flag to remind us.

**Comment by mbbroberg** [comment]
We got what we need from this discussion. Thanks everyone ✌
