### ISSUE TITLE
Document naming conventions for various plugin artifacts

### ISSUE THREAD

**Issue by majormoses** [sensu-plugins/community#68]
We have very sparse development guideline or help documents to help people navigate the sea of sensu plugins. We should document some helpful guidelines for first time users as well as contributors of plugins sane naming conventions.

Relates:
- https://github.com/sensu-plugins/sensu-plugins-mysql/issues/63
- https://github.com/sensu-plugins/sensu-plugins-mysql/issues/64

**Comment by eheydrick** [comment]
There's https://github.com/sensu-plugins/documentation/blob/master/docs/developer_guidelines.md#naming-conventions documenting that. Could prob expand on it some more.
