### ISSUE TITLE
Create sensu-plugins-chatwork repo

### ISSUE THREAD

**Issue by tsubauaaa** [sensu-plugins/community#7]
Please create a repository for chatwork . Chatwork is a chat tool that can be used on the Internet .

Chatwork is here .
https://www.chatwork.com

Repository is here .
https://github.com/tsubauaaa/sensu-plugin-chatwork

**Comment by eheydrick** [comment]
@tsubauaaa I have created https://github.com/sensu-plugins/sensu-plugins-chatwork with boilerplate. Send a PR with the new plugins and we'll get them merged in. I'm still working on getting travis-ci setup for it, should have it soon.
