### ISSUE TITLE
New repo skel for sensu-plugins-azure

### ISSUE THREAD

**Issue by jpoizat** [sensu-plugins/community#72]
## Transfer Ownership

We would like to transfer the ownership of this plugin to the sensu-plugins organization in hopes of better community support and exposure. I have reviewed [the skeleton plugin](https://github.com/sensu-plugins/sensu-plugins-skel) for best practices.

Repo to transfer:

I am also interested in continuing to help as a maintainer of this plugin 👍

**Comment by majormoses** [comment]
I have created the repo I will get the skel in hopefully tonight.

**Comment by majormoses** [comment]
I got the skel pushed. As I went to rubygems.org to push the skel I found this: https://github.com/tombuildsstuff/sensu-plugins-azurerm maybe we shuld transfer that one over instead.

**Comment by majormoses** [comment]
I have opened an issue to see if we can transfer the repo and start off with some real checks!

**Comment by jpoizat** [comment]
thanks ! will have a look deeper today a bit

**Comment by mbbroberg** [comment]
👏 👏 👏 👏  so cool to have this joining the Sensu Plugin family 👏 👏 👏 👏

**Comment by majormoses** [comment]
Looks like we are gonna transfer over the other (azurerm) one and do the same type of skel setup. Figured it's better to have a decent starting place.

**Comment by jpoizat** [comment]
sorry been a bit overloaded recently... would that make sense to paste what I currently have but barely usable and requiring a lot of rework or me spending more time before posting it ? fine for me to integrate it with the existing azurerm ones. :)

**Comment by majormoses** [comment]
well we are still waiting for it to transfer over so if you feel you need to re-work it then I'd say just keeping hacking at locally until you are ready. Hopefully it should transfer in the next day or so and then you can fork it and start working on it there.

**Comment by majormoses** [comment]
I have transferred the repo over. I will deprecate the `azure` repo in favor of `azurerm` and will do a lot of the general setup stuff within the next week or so. You can certainly start taking a look at what you want to modify you just might want to give me a few days so you are not looking at a nasty rebase after doing things like appeasing the `rubocop`s.

**Comment by majormoses** [comment]
I have created https://github.com/sensu-plugins/sensu-plugins-azurerm/pull/14 to get all the standard stuff that community plugins need. After this lands I would start making PRs and adding tests. I am gonna close this out and mark the `sensu-plugins-azure` repo `deprecated` with a link to `sensu-plugins-azurerm`

**Comment by majormoses** [comment]
https://github.com/sensu-plugins/sensu-plugins-azurerm/pull/15
