### ISSUE TITLE
Maintainer Wanted: Windows focus

### ISSUE THREAD

**Issue by mbbroberg** [sensu-plugins/community#74]
The current maintainer team is in need of a friendly face to lead our Windows-centric efforts. In particular: 

* Speak up on Sensu on Windows matters as they come up
* Familiarity with administration and maybe a touch of Powershell
* Follow activity on the [Windows Plugins](https://github.com/sensu-plugins/sensu-plugins-windows) repo
* Participate in a `#windows` (not yet made) channel on [Community Slack](http://slack.sensu.io)

**Maintainers are asked to help by:** 
- Weighing in on key initiatives
- Participation on issues/pull requests
- Providing feedback to guidelines
- Being a leader: raising up important opportunities, prioritize less important ones
- Sharing your expertise 

**Maintainers are NOT expected to be:** 
- Sensu Experts: not everyone knows everything about Sensu. You will definitely learn by volunteering 😄 
- Open Source experts: we're all learning by doing here and will mentor you on git/GitHub
- On call or under a SLA: these are volunteer roles. Communication when you're too busy to participate is sincerely appreciated, but daily participation is not an expectation
- Participate forever: we love when people have the time to participate and understand when you no longer have that time. Give back while you can and rest assured that we'll take it back over when you get busy

**Maintainers get:** 
- Unique opportunities to influence the project
- Exclusive channels of communication to grow your Sensu expertise
- Access to paid tools as needed for us to succeed as maintainers
- An expert partner in community management (from code management to people management)
- Mentorship, as requested, in public speaking, blogging, and social media
- Priority opportunities to speak, blog and participate with Sensu Inc
- Tons of guidelines that will make your work easier
- To hangout with a lovely bunch of peers who are sharing in the #monitoringlove ✌

We would love **at least one**, but could be as many skilled community members as they are available. Please raise your hand here or mention others you think would be great contributors!

**Comment by mbbroberg** [comment]
I should say, I consider SaltStack part of the Windows focus due to the prevalence of users who do both. Now I could be totally wrong in lumping them together and I welcome feedback from those interested in maintainer one or the other 👍

**Comment by mbbroberg** [comment]
Moved the SaltStack portion into its own issue: #79

**Comment by absolutejam** [comment]
I didn't know SaltStack was really prevalent on Windows, but I guess I can't really talk because I use SaltStack and Windows :thinking: 

Anyway, I manage almost exclusively Wndows (Poor me) and I'm pushing Sensu to a larger install base so I'll be happy to help out! I'm working on something a bit more templated for Windows checks, but I'm trying to focus on getting pretty comprehensive Pester tests because I'm getting constantly annoyed with odd Powershellisms.

**Comment by mbbroberg** [comment]
Excellent! Adding you to the page @absolutejam 👌

**Comment by mbbroberg** [comment]
We now have one maintainer helping Windows along as well as @perlchild who volunteered to keep an eye out. Closing!
