### ISSUE TITLE
Maintainer Wanted: Chef

### ISSUE THREAD

**Issue by mbbroberg** [sensu-plugins/community#75]
The current maintainer team needs more support on the Chef cookbooks for Sensu so @majormoses can focus on the broader Plugins organization. If you know Chef and have time to help us, please let us know here! You'll have the advantage of Ben being very familiar with the technology and there to help. 

**Maintainers are asked to help by:** 
- Weighing in on key initiatives
- Participation on issues/pull requests
- Providing feedback to guidelines
- Being a leader: raising up important opportunities, prioritize less important ones
- Sharing your expertise 

**Maintainers are NOT expected to be:** 
- Sensu Experts: not everyone knows everything about Sensu. You will definitely learn by volunteering 😄 
- Open Source experts: we're all learning by doing here and will mentor you on git/GitHub
- On call or under a SLA: these are volunteer roles. Communication when you're too busy to participate is sincerely appreciated, but daily participation is not an expectation
- Participate forever: we love when people have the time to participate and understand when you no longer have that time. Give back while you can and rest assured that we'll take it back over when you get busy

**Maintainers get:** 
- Unique opportunities to influence the project
- Exclusive channels of communication to grow your Sensu expertise
- Access to paid tools as needed for us to succeed as maintainers
- An expert partner in community management (from code management to people management)
- Mentorship, as requested, in public speaking, blogging, and social media
- Priority opportunities to speak, blog and participate with Sensu Inc
- Tons of guidelines that will make your work easier
- To hangout with a lovely bunch of peers who are sharing in the #monitoringlove ✌

We would love **at least one**, but could be as many skilled community members as they are available. Please raise your hand here or mention others you think would be great contributors!

**Comment by thomasriley** [comment]
I am interested in volunteering and helping out here. I’m a big fan of both Sensu and Chef :)

**Comment by majormoses** [comment]
Have my blessing, before granting privileges to the repo I should probably sit down with him and discuss the project conventions and such.

**Comment by mbbroberg** [comment]
@thomasriley you have the 2 +1s we require to get started! We'll start the onboard process today 🎉 💥
