### ISSUE TITLE
Create sensu-plugins-json-metrics repo

### ISSUE THREAD

**Issue by sczizzo** [sensu-plugins/community#8]
Sensu-Plugins-JSON-Metrics gathers metrics from any JSON metrics endpoint by traversing the
response and flattening the keys into a Graphite-compatible format, e.g.

```
{
  "just": {
    "a": {
      "test": 0
    }
  },
  "whats": [
    { "this": 0 },
    "oops",
    { "this": 1 },
    { "that": 2 }
  ],
  "another": 1
}
```

Will be converted to something like this:

```
hostname.metrics.just.a.test 0 1234567890
hostname.metrics.whats.0.this 0 1234567890
hostname.metrics.whats.1.this 1 1234567890
hostname.metrics.whats.2.that 2 1234567890
hostname.metrics.another 1 1234567890
```

In the most basic form, just shoot it at an endpoint:

```
$ metrics-json.rb --uri 'http://app.dev/v1/metrics.json' --scheme 'app.dev.metrics'
```

This plugin supports more advanced URIs, and there are a couple extra options
you may wanna check out:

```
$ metrics-json.rb \
  --convert-booleans \
  --replace-dots \
  --unknown-on-empty \
  --uri 'https://user:pass@app.dev/v2/metrics.json' \
  --scheme 'app.dev.metrics'
```

The plugin is currently hosted in a personal repository:
https://github.com/sczizzo/sensu-plugins-json-metrics

**Comment by eheydrick** [comment]
Hey @sczizzo. This is a sweet plugin! After some discussion we think this plugin would be best located in the [sensu-plugins-http](https://github.com/sensu-plugins/sensu-plugins-http) repo. That way we keep similar plugins grouped together. Can you send a PR in that repo and we'll get it merged.
