### ISSUE TITLE
Maintainers Wanted: Ansible

### ISSUE THREAD

**Issue by mbbroberg** [sensu-plugins/community#80]
The current maintainer team is in need of a friend to lead on Ansible efforts. In particular: 

* Guide the right on Sensu + Ansible matters, helping Sensu users get the best experience
* Follow activity on the [Ansible](https://github.com/sensu/sensu-ansible) repo 
* Participate in the `#ansible` channel on [Community Slack](http://slack.sensu.io)

**Maintainers are asked to help by:** 
- Weighing in on key initiatives
- Participation on issues/pull requests
- Providing feedback to guidelines
- Being a leader: raising up important opportunities, prioritize less important ones
- Sharing your expertise 
- Hanging out in our Community Slack

**Maintainers are NOT expected to be:** 
- Sensu Experts: not everyone knows everything about Sensu. You will definitely learn by volunteering 😄 
- Open Source experts: we're all learning by doing here and will mentor you on git/GitHub
- On call or under a SLA: these are volunteer roles. Communication when you're too busy to participate is sincerely appreciated, but daily participation is not an expectation
- Participate forever: we love when people have the time to participate and understand when you no longer have that time. Give back while you can and rest assured that we'll take it back over when you get busy

**Maintainers get:** 
- Unique opportunities to influence the project
- Exclusive channels of communication to grow your Sensu expertise
- Access to paid tools as needed for us to succeed as maintainers
- An expert partner in community management (from code management to people management)
- Mentorship, as requested, in public speaking, blogging, and social media
- Priority opportunities to speak, blog and participate with Sensu Inc
- Tons of guidelines that will make your work easier
- To hangout with a lovely bunch of peers who are sharing in the #monitoringlove ✌

We would love **at least one**, but could be as many skilled community members as they are available. Please raise your hand here or mention others you think would be great contributors!

**Comment by mbbroberg** [comment]
@cmacrae our hats go off to you for starting this work! We are so thankful as a community that you did. If you do have time to stay on as a maintainer you are more than welcome to do so. 

@smuth4 I see you have write access as well. I'd love to add you to what's shaping up to be a legit maintainer program for Sensu projects 😄. Are you still interested?

Hey @jaredledvina and @tculp, I've noticed you both have a lot of PRs waiting for merge. Are either of you interested?

Any and all of you can ping me here, on [community Slack @matt](http://slack.sensu.io) or via email to community`@sensu.io`. Cheers! ❤️

**Comment by jaredledvina** [comment]
Hey @mbbroberg,
I'm more than happy to help assist with the https://github.com/sensu/sensu-ansible repo in anyway possible. I have have a pile of ideas on how Sensu can better help out the Ansible community at large (with this specific repo but also looking into supporting the native Ansible `sensu*` modules). I'll note upfront that I don't have a _ton_ of spare time but, will do my best to help out with the time I have. If you'd like to discuss this on the community Slack feel free to reach out!

**Comment by cmacrae** [comment]
Hey @mbbroberg 👋   

Thanks for bringing this up! Happy to see others getting use out of my work and even happier to see  folks at Sensu and the community continuing my efforts!  

I'll certainly be happy to stick around as a maintainer 👍

**Comment by smbambling** [comment]
There are a few Ansible modules for Sensu, it would be nice to review the current code and see what can/should be moved more into a module vs roles.  

Hopefully this would streamline the setup and complexity.

**Comment by mbbroberg** [comment]
@smbambling love the input. @jaredledvina mentioned to me he's going to write up a RFC on that. I'd love for you both to do so and compare notes. Something like: 

```
## Challenge
What you see as the challenge
## Proposal
Proposed changes
```

or `## Current State` / `## Desired State`. Your call. Add it as an issue here if it spans multiple repositories or add it to the repo in question (ex. https://github.com/sensu/sensu-ansible/issues).

**Comment by jaredledvina** [comment]
Following up here, opened https://github.com/sensu/sensu-ansible/issues/118 with some thoughts, ramblings, and my general perspective on how we can create a stronger Ansible community around Sensu.

**Comment by flxwu** [comment]
Dear @mbbroberg and Sensu-Ansible Team,

in case you are still searching for maintainers, please consider adding the sensu-ansible repo on [maintainerswanted.com](https://maintainerswanted.com) 😄 It's a site that I built inspired by a tweet by Sara Viera and I am about to launch it in the next few days, it'd be really cool to already have some projects onboard till then!

Thanks!

Best,
Felix

**Comment by majormoses** [comment]
@flxwu we now have some coverage for the ansible stuff, we do need to find a `windows` plugin and `saltstack` maintainers. And in general we need more overall `ruby` and `python` plugin maintainers. I will check out the site.
