### ISSUE TITLE
Create sensu-plugins-gearman repository

### ISSUE THREAD

**Issue by insom** [sensu-plugins/community#9]
Hi,

I've created a set of basic gearman plugins modelled on the `sensu-plugins-beanstalk` repository - can a new repository please be created for it? I'm hosting it on my personal GitHub for now:

https://github.com/insom/sensu-plugins-gearman

Regards,

Aaron

**Comment by eheydrick** [comment]
Hey @insom, I created https://github.com/sensu-plugins/sensu-plugins-gearman from your repo and added the rest of the boilerplate. I'm still working on getting it setup in travis-ci and should have it soon. Thanks for the contribution!
