### ISSUE TITLE
[RFC] travis images stable or shiny

### ISSUE THREAD

**Issue by majormoses** [sensu-plugins/community#90]
## Options

There are some pretty interesting things regarding travis build images please read the full post [here](https://blog.travis-ci.com/2017-12-01-new-update-schedule-for-linux-build-images).

- specify `group: trusty`: trusty images (current default) will be frozen in a month no further updates
- no change: new travis default of `group: travis_lts`: I this as the name would imply would be the stable and least effort to accomplish. This is likely the one that makes the most sense.
- change `group: travis_latest`: "frequent" releases (once a month)

### Stability
I think we should probably just accept the default and hope nothing breaks. The more time I have to spend managing CI the less I am reviewing, fixing bugs, writing doc,
adding features, etc. We might eventually need to switch over later due to old packages, language support, security, etc but I'd like to take a wait and see approach.

### Living on the "edge"
I do generally like living somewhere near the edge as it means that by the time changes hits my production systems I have familiarized myself with changes. That being said, it's a decent investment without seeing all the cards on the table.

**Comment by mbbroberg** [comment]
I'm leaning toward stable but glad to explore the new excitement too. Others?

**Comment by jaredledvina** [comment]
Personally, I'd also say stable, it'd actually be pretty cool to do both, where tests **must** pass on stable but, optionally pass on latest and just flag it as 'hey, in the future things might blow up!'.

**Comment by majormoses** [comment]
> it'd actually be pretty cool to do both, where tests must pass on stable but, optionally pass on latest and just flag it as 'hey, in the future things might blow up!'.

Indeed an intriguing thought, I don't know the feasibility of soft failing `latest` but not with `lts` currently. I am sure we could accomplish this by wrapping with a `|| true` on any calls on `latest` but I think we would wait for a feature enhancement to do that. I would think that they probably would not be inclined to add such a feature lightly without the demand that is willing to pay as this may effectively double their infrastructure resources per project that utilizes this. Also this would slow down as we only get so many parallel builds and this effectively would increase the time it takes as there would be time sitting in queue.

We are very thankful to the **awesome** folks at travis-ci that do a lot to support open source initiatives such as `sensu` free of charge and I'd hate to ask them to incur the additional cost.

> I'm leaning toward stable

Agreed, I think that is a prudent approach _right now_ as we have a lack of data and per their description of:
> If you’re working on a larger scale project or simply require a specific, long-term-support version of your packages, `group: travis_lts` is what you’re looking for

Says it all until we find something that is compelling enough.

**Comment by mbbroberg** [comment]
Looks like we're all suckers for stability 😄. Is there a place we should document the decision here before closing @majormoses ?

**Comment by majormoses** [comment]
I think it should probably be mentioned somewhere in the testing docs that do not exist yet. I will try to remember to include this somewhere when I find the time to write that up. If you want to keep this open until it is documented just re-open or comment if you can't and we will re-open.
