### ISSUE TITLE
[RFC] Slack activity channel for Infrastructure Code repos

### ISSUE THREAD

**Issue by thomasriley** [sensu-plugins/community#91]
We have the `plugins-activity` channel in the community Slack as a useful way of tracking changes on the Sensu Plugin repos however we do not have an equivalent for infrastructure code repos.

We should consider having slack channels for the different infrastructure code repos we maintain. This could be a generic channel such as `infrastructure-code-activity` (I'm not precious about the name if someone has a better suggestion). Alternatively we could have specific channels for the different technologies such as `chef-activity` & `puppet-activity` etc.

I would personally prefer the latter apporach as I care to monitor the chef changes via a slack channel bit unlikely I would need to monitor changes for puppet, salt stack, etc. 

Anyone have any further thoughts on this?

**Comment by jaredledvina** [comment]
I personally prefer the latter as well and am happy to wire up the sensu-ansible repo.

**Comment by majormoses** [comment]
Ya I'd prefer more specific ones as well.

**Comment by mbbroberg** [comment]
The balance of channel proliferation and signal to noise ratio are important. One question to be sure I follow: is there any reason we can't have that feed in the main channels of `#chef` or `#puppet`? If it's really active, we can switch it to dedicated channels. If not though, it's nice to have one channel to look at IMO. 

Thoughts @thomasriley @jaredledvina @majormoses ?

**Comment by majormoses** [comment]
So we had a discussion in the community chat about this here are the high level takeaways:
- if the volume is low enough then push it to the main channel. IE `#chef`, `#ansibile`, etc
- if the volume is high enough (metric we decided in chat was 5 per day on average over a week) then it should have a "sidecar" channel.

Naming is still up for debate, here were some proposed naming conventions for any "sidecar" channels:
- `contributing-$THING` (apply below variations here)
- `$THING-contributing`
- `$THING-activity`
- `$THING-github`
- `$THING-feed`
- `$THING-raw`
- `$THING-maintainers`
- `$THING-sidecar`

**Comment by jaredledvina** [comment]
I'm game to have `sensu-ansible` wired up to the `#ansible` room and move it if it gets too noisy for folks. 👍  from me, I don't know if I can 'just do this' but, let me know if I can!

**Comment by majormoses** [comment]
Unsure if you have enough access to do the slack side but if not I can do that part for you if needed. Hit me up in slack and we can work out the details.

**Comment by absolutejam** [comment]
Will the integration just track the canonical `sensu-` repo (eg. `sensu-chef`) or would it be pertinent to add integrations to any related repos?

Also, I'd like to request it for the saltstack channel. I'm not an admin or anything, but I've got the most posts in there (quantity over quality :wink:) so I hope that counts for something!

**Comment by majormoses** [comment]
I'd vote that it should be any related repos. For example the `#chef` channel might include:
- https://github.com/sensu/sensu-chef
- https://github.com/sensu/uchiwa-chef
- https://github.com/sensu-plugins/sensu-plugins-chef

**Comment by majormoses** [comment]
I will chat with @mbbroberg on the salt one as we don't currently have a maintainer nor do I have access to that repo.

**Comment by majormoses** [comment]
I have updated the `#chef` ones since I have access for others I will expect those with access to the respective repos to reach out to me for help if they need it.

**Comment by majormoses** [comment]
I have added for the plugins and worked with @jaredledvina to get the actual role/playbook repo added. 
I went for the following defaults:
![image](https://user-images.githubusercontent.com/3145127/33911582-b4d170e4-df47-11e7-9f62-a08e824646df.png)
I think these are sensible defaults for all but the overall plugins sidecar channel. On those I tend to be a bit more _restrictive_ to avoid say 200 notifications when a new maintainer is added to plugins but when you have a handful of repos that are targeted I think there is value in displaying new maintainers on projects if the noise ratio is low enough.

**Comment by majormoses** [comment]
I have created the integration for the puppet module repo but will need Garret to do the last mile config that I do not have access to. I have hooked up the plugin though.

**Comment by ghoneycutt** [comment]
https://github.com/sensu/sensu-puppet added

Thanks @majormoses

**Comment by majormoses** [comment]
puppet is done. I'd like to close this right now and work on any other outliers ad-hoc now that we have a sane set of guidelines.

**Comment by mbbroberg** [comment]
For consistency, I did this in Salt too with the following:


<img width="647" alt="screen shot 2017-12-12 at 4 29 49 pm" src="https://user-images.githubusercontent.com/1744971/33915793-16734ca2-df5a-11e7-9b2e-1c4d76019285.png">

**Comment by mbbroberg** [comment]
I also forgot to mention this is documented in #92
