### ISSUE TITLE
Request to add Sendgrid to the Sensu Plugins Family 

### ISSUE THREAD

**Issue by itdevon** [sensu-plugins/community#96]
Can someone create a skeleton repo named sensu-plugin-sendgrid. I have the old handler code, I would like to PR up to it for appoval. 

Right now the handler is having issues with the new sensu filters and I also noticed the plugin is not being maintained anymore. 
Please let me know if I'm doing this wrong.

**Comment by mbbroberg** [comment]
Hey @Devon21! This request coming into here is exactly right. I'm happy to make a repo and hand it off to you to fill in the details.

**Comment by mbbroberg** [comment]
@Devon21 for reference, where's the source of the one plugin not being maintained?

**Comment by itdevon** [comment]
The only one I can find is my local one, that I have been using for about 2 years. I thought for sure there was a sendgrid repo in the old sensu plugin area, but not 100%

**Comment by majormoses** [comment]
@mbbroberg that is part of the problem we are not sure the original source it existed in his infrastructure but neither of us are sure of the source. I checked the plugins org, legacy plugins repo, and sendgrid ops org. We decided that the best thing was to give it a home so that it is not lost again at the cost of lack of attribution of efforts.

**Comment by mbbroberg** [comment]
No worries - skel coming up in :ok_hand:

**Comment by mbbroberg** [comment]
@Devon21 still doing initial config (including Travis) but it's all yours! You have write privileges: https://github.com/sensu-plugins/sensu-plugins-sendgrid

Please use the checklist in the current README.md and then replace it with the README-skel.md when you're ready! And say hi in the `#contributing` channel [in Slack](slack.sensu.io) if you don't mind 😄

**Comment by majormoses** [comment]
@Devon21 please note that while we are giving you write access we ask that you still submit your changes through normal pull request process. If other maintainers are not reviewing your work in a timely manner poke them and if they are not responding poke me and bring it up in slack.

**Comment by majormoses** [comment]
@mbbroberg looks like some things still need to be updated such as the gemspec name as it still says skel.

**Comment by mbbroberg** [comment]
@majormoses yep, I copied the base skel over and trusting @Devon21 to tackle the switch over. Title of the repo is UNDER CONSTRUCTION and tagged as such so feel it's clear enough to let him work on rev1.

**Comment by mbbroberg** [comment]
Hey @itdevon, I see you pushed the code in. Awesome! 👏 

Will you be able to keep going on updating the usage documentation and setting up the repo on your own or do you need some help?

**Comment by majormoses** [comment]
this has been done.
